# EDA

In [13]:
import pandas as pd

df = pd.read_csv("data/raw/Airbnb_Open_Data.csv")

print(df.shape)
df.head()

(102599, 26)

C:\Users\Dunith Munasinghe\AppData\Local\Temp\ipykernel_3232\306497710.py:3: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("data/raw/Airbnb_Open_Data.csv")

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  object
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  object
 4   host name                       102193 non-null  object
 5   neighbourhood group             102570 non-null  object
 6   neighbourhood                   102583 non-null  object
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  object
 10  country code                    102468 non-null  object
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  object
 13  room type                       102599 non-null  object
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  object
 16  service fee                     102326 non-null  object
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   object
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   object
 25  license                         2 non-null       object
dtypes: float64(9), int64(2), object(15)
memory usage: 20.4+ MB

In [15]:
df.describe()

,id,host id,lat,long,Construction year,minimum nights,number of reviews,reviews per month,review rate number,calculated host listings count,availability 365
count,1.025990e+05,1.025990e+05,102591.000000,102591.000000,102385.000000,102190.000000,102416.000000,86720.000000,102273.000000,102280.000000,102151.000000
mean,2.914623e+07,4.925411e+10,40.728094,-73.949644,2012.487464,8.135845,27.483743,1.374022,3.279106,7.936605,141.133254
std,1.625751e+07,2.853900e+10,0.055857,0.049521,5.765556,30.553781,49.508954,1.746621,1.284657,32.218780,135.435024
min,1.001254e+06,1.236005e+08,40.499790,-74.249840,2003.000000,-1223.000000,0.000000,0.010000,1.000000,1.000000,-10.000000
25%,1.508581e+07,2.458333e+10,40.688740,-73.982580,2007.000000,2.000000,1.000000,0.220000,2.000000,1.000000,3.000000
50%,2.913660e+07,4.911774e+10,40.722290,-73.954440,2012.000000,3.000000,7.000000,0.740000,3.000000,1.000000,96.000000
75%,4.320120e+07,7.399650e+10,40.762760,-73.932350,2017.000000,5.000000,30.000000,2.000000,4.000000,2.000000,269.000000
max,5.736742e+07,9.876313e+10,40.916970,-73.705220,2022.000000,5645.000000,1024.000000,90.000000,5.000000,332.000000,3677.000000

In [16]:
df.isnull().sum()

id                                     0
NAME                                 250
host id                                0
host_identity_verified               289
host name                            406
neighbourhood group                   29
neighbourhood                         16
lat                                    8
long                                   8
country                              532
country code                         131
instant_bookable                     105
cancellation_policy                   76
room type                              0
Construction year                    214
price                                247
service fee                          273
minimum nights                       409
number of reviews                    183
last review                        15893
reviews per month                  15879
review rate number                   326
calculated host listings count       319
availability 365                     448
house_rules                        52131
license                           102597
dtype: int64

# Handling Missing Values

In [17]:
missing = df.isnull().sum().sort_values(ascending=False)
missing_pct = (missing / len(df)) * 100

missing_df = pd.DataFrame({
    "missing_count": missing,
    "missing_percent": missing_pct
})

missing_df.head(20)

                                missing_count  missing_percent
license                                102597        99.998051
house_rules                             52131        50.810437
last review                             15893        15.490404
reviews per month                       15879        15.476759
country                                   532         0.518524
availability 365                          448         0.436651
minimum nights                            409         0.398639
host name                                 406         0.395715
review rate number                        326         0.317742
calculated host listings count            319         0.310919
host_identity_verified                    289         0.281679
service fee                               273         0.266084
NAME                                      250         0.243667
price                                     247         0.240743
Construction year                         214         0.208579
number of reviews                         183         0.178364
country code                              131         0.127682
instant_bookable                          105         0.102340
cancellation_policy                        76         0.074075
neighbourhood group                        29         0.028265

### Dropped Columns and Justification

1. **license**
   - Contains ~100% missing values.
   - Provides no usable signal for modeling.
   - Including this feature would introduce noise without predictive value.

2. **house_rules**
   - High missing rate (~50%) and unstructured text format.
   - Requires advanced NLP processing, which is out of scope for the current phase.
   - Low direct impact on pricing and demand modeling relative to complexity.

3. **host_name**
   - Identifier-type feature with no intrinsic predictive meaning.
   - Does not generalize across listings and may introduce unnecessary variance.

4. **NAME**
   - Listing title (textual feature) requiring NLP for meaningful extraction.
   - High dimensionality and noise risk without proper text processing.
   - Not critical for baseline pricing and demand models.

5. **country_code**
   - Redundant feature since `country` already captures the same information.
   - Keeping both would introduce multicollinearity without added value.

6. **construction_year**
   - Potentially useful but often noisy/inconsistent in real-world datasets.
   - Requires transformation (e.g., property age) and validation.
   - Dropped at this stage to maintain data reliability and simplicity.

In [18]:
df.shape

(102599, 26)

In [19]:
columns_to_drop = [
    "license",
    "house_rules",
    "host name",
    "NAME",  
    "country code",
    "Construction year"
]

df = df.drop(columns=columns_to_drop)

print("Remaining columns:", df.columns.tolist())

Remaining columns: ['id', 'host id', 'host_identity_verified', 'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country', 'instant_bookable', 'cancellation_policy', 'room type', 'price', 'service fee', 'minimum nights', 'number of reviews', 'last review', 'reviews per month', 'review rate number', 'calculated host listings count', 'availability 365']

In [20]:
df.shape

(102599, 20)

### Missing Value Imputation Strategy

The following numerical features contain a very small percentage of missing values (<1%). 
Given their importance in pricing and demand modeling, we apply **median imputation**.

#### Rationale for Median Imputation

1. **availability_365**
   - Represents the number of days a listing is available per year.
   - Can contain skewed values (e.g., always available vs rarely available).
   - Median is robust to outliers and preserves distribution.

2. **minimum_nights**
   - Indicates booking constraints set by hosts.
   - Typically right-skewed (few listings have very high minimum nights).
   - Median avoids distortion from extreme values.

3. **review_rate_number**
   - Reflects user ratings (trust/quality signal).
   - Important for demand prediction.
   - Median maintains central tendency without bias from outliers.

4. **calculated_host_listings_count**
   - Proxy for host experience or professionalism.
   - Distribution is usually skewed (few hosts own many listings).
   - Median prevents over-influence from large commercial hosts.

5. **price**
   - Core variable for pricing and revenue modeling.
   - Must not be dropped due to missing values.
   - Median imputation ensures stability without introducing bias from extreme listings.

#### Summary

- Missing percentage is very low → safe to impute.
- Median is chosen due to:
  - robustness to skewness
  - resistance to outliers
  - preservation of realistic distribution

In [21]:
cols_median = [
    "availability 365",
    "minimum nights",
    "review rate number",
    "calculated host listings count"
]

for col in cols_median:
    df[col].fillna(df[col].median())

print("Missing values after imputation:")
print(df[cols_median].isnull().sum())

Missing values after imputation:
availability 365                  448
minimum nights                    409
review rate number                326
calculated host listings count    319
dtype: int64

In [22]:
# Clean and convert price
df["price"] = (
    df["price"]
    .replace(r"[\$,]", "", regex=True)
    .astype(float)
)

# Clean and convert service_fee
df["service fee"] = (
    df["service fee"]
    .replace(r"[\$,]", "", regex=True)
    .astype(float)
)

# Fill missing values with median
df["price"].fillna(df["price"].median(), inplace=True)
df["service fee"].fillna(df["service fee"].median(), inplace=True)

# Check
print(df[["price", "service fee"]].isnull().sum())
print(df[["price", "service fee"]].head())

price          0
service fee    0
dtype: int64
   price  service fee
0  966.0        193.0
1  142.0         28.0
2  620.0        124.0
3  368.0         74.0
4  204.0         41.0

C:\Users\Dunith Munasinghe\AppData\Local\Temp\ipykernel_3232\1555968220.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["price"].fillna(df["price"].median(), inplace=True)
C:\Users\Dunith Munasinghe\AppData\Local\Temp\ipykernel_3232\1555968220.py:17: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["service fee"].fillna(df["service fee"].median(), inplace=True)

In [23]:
# Check missing values for specific columns
print("Missing values count:")
print(df[["price", "service fee"]].isnull().sum())

# Also check percentage (more informative)
missing_pct = df[["price", "service fee"]].isnull().mean() * 100
print("\nMissing values percentage:")
print(missing_pct)

Missing values count:
price          0
service fee    0
dtype: int64

Missing values percentage:
price          0.0
service fee    0.0
dtype: float64

In [27]:
cols_mode = [
    "instant_bookable",
    "neighbourhood group"
]

for col in cols_mode:
    mode_value = df[col].mode()[0]
    df[col].fillna(mode_value, inplace=True)

# Check
print(df[cols_mode].isnull().sum())

instant_bookable       0
neighbourhood group    0
dtype: int64

In [31]:
# Standardize values first
df["cancellation_policy"] = df["cancellation_policy"].str.lower().str.strip()

# Get mode
mode_value = df["cancellation_policy"].mode(dropna=True)[0]

# Fill missing values
df["cancellation_policy"] = df["cancellation_policy"].fillna(mode_value)

# Check
print(df["cancellation_policy"].isnull().sum())
print("Mode used:", mode_value)

0
Mode used: moderate

In [32]:
missing = df.isnull().sum().sort_values(ascending=False)
missing_pct = (missing / len(df)) * 100

missing_df = pd.DataFrame({
    "missing_count": missing,
    "missing_percent": missing_pct
})

missing_df.head(20)

                                missing_count  missing_percent
last review                             15893        15.490404
reviews per month                       15879        15.476759
country                                   532         0.518524
availability 365                          448         0.436651
minimum nights                            409         0.398639
review rate number                        326         0.317742
calculated host listings count            319         0.310919
host_identity_verified                    289         0.281679
number of reviews                         183         0.178364
neighbourhood                              16         0.015595
long                                        8         0.007797
lat                                         8         0.007797
neighbourhood group                         0         0.000000
host id                                     0         0.000000
id                                          0         0.000000
instant_bookable                            0         0.000000
price                                       0         0.000000
room type                                   0         0.000000
cancellation_policy                         0         0.000000
service fee                                 0         0.000000

In [34]:
df["country"].fillna("United States")

print(df["country"].isnull().sum())
print(df["country"].value_counts().head())

0
country
United States    102599
Name: count, dtype: int64

In [36]:
cols_zero = ["reviews per month", "number of reviews"]

for col in cols_zero:
    df[col].fillna(0, inplace=True)

# Verify
print(df[cols_zero].isnull().sum())

reviews per month    0
number of reviews    0
dtype: int64

C:\Users\Dunith Munasinghe\AppData\Local\Temp\ipykernel_3232\263299180.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(0, inplace=True)